version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"


sphinx:
  builder: html
  configuration: _doc/conf.py
  fail_on_warning: false

    #fail_on_warning: true


python:
  install:
   - requirements: _doc/requirements.txt
      
formats:
  - pdf
  - epub
submodules:
  include:
    - _translated
    - _doc
  recursive: true
