language: ruby
dist: trusty
rvm:
 - 2.5
install: git clone -b ${TRAVIS_BRANCH} https://github.com/${TRAVIS_REPO_SLUG%%/*}/qubesos.github.io ~/qubesos.github.io
script: ~/qubesos.github.io/_utils/travis.sh
addons:
  apt:
    # These must be kept in sync with the .travis.yml in submodules
    packages:
    - hunspell
    - pandoc
    - jq
notifications:
  email:
    recipients:
      - qubedmaiska@protonmail.com
    on_success: always
    on_failure: always
